config/routes.rb
Rails.application.routes.draw do
  get 'all_users/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index'
resources :posts do	
	# resources :comments
	member do 
		post :like
		post :unlike
		get :all_likes
		post :comment
		post :remove_comment
		get :user_profile
	end
	collection do		
		get :my_post
	end
	
end
# resources :likes do
# 	collection do
# 		get :all_likes
# 	end
# end
resources :friendships do
	member do
		post :accept
		post :reject
	end
	collection do 
		get :myfriends
	end
end
resources :conversations do 
	resources :messages
end
# mount ActionCable.server => '/cable'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	 belongs_to :sender, :foreign_key => :sender_id, :class_name => "User"
 	 belongs_to :recipient, :foreign_key => :receiver_id, :class_name => "User"
	has_many :messages, dependent: :destroy


	def opposed_user(user)
   		 user == recipient ? sender : recipient
  	end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def index
		@conversations=Conversation.all
	end
	def create
		@curr=current_user.id
		@other_user=User.find(params[:other_user])
		@conversation=Conversation.where('(sender_id = ? AND receiver_id = ? ) OR (sender_id = ? AND receiver_id = ? )', current_user.id, @other_user.id,  @other_user.id, current_user.id).present?
		if @conversation == true
			render :message
		else
			@conversation= Conversation.create(sender_id: current_user.id,receiver_id: @other_user.id)
			if @conversation.save
				render :message
			else
				redirect_to root_path
			end
		end
	end	
	def param_conv
		params.require(:conversation).permit(:sender_id,:receiver_id)
	end

	
end
# create(sender_id: current_user.id,receiver_id: @other_user.id)

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="container">  
  <table class="table" border="1">
    <thead>
      <tr>
        <th>Chat User</th>
        <th>All User</th>
      </tr>
    </thead>
    <tbody>
      <tr style=" border-color: inherit;">
        <td> 
          <ul id="conversations-list">
            <% @conversations.each do |conversation| %>
            <% if conversation.sender_id == current_user.id || conversation.receiver_id == current_user.id %>
            <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.receiver_id) %>
            <li>
              <%= image_tag(recipient.image,style: "height: 42px;border-top-left-radius: 8px;border-radius: 10px;") %>
              <%= link_to recipient.name.titleize ,conversation_messages_path(conversation)%></li>
              <% else %>
              <% recipient = User.find(conversation.sender_id) %>
              <li>
                <%= image_tag(recipient.image,style: "height: 42px;border-top-left-radius: 8px;border-radius: 10px;") %>
                <%= link_to recipient.name.titleize,conversation_messages_path(conversation)%>
              </li>
              <% end %>        
              <% end %>
              <% end %>   
            </ul>
        </td>
        <td>
        	<ul>
        		<% User.all.each do |other_user| %>
        		<% if other_user != current_user %>
        		<li>
        			<%= link_to(conversations_path(:other_user => other_user.id), method: :POST  ) do %>
               <%= image_tag(other_user.image,style: "height: 42px;border-top-left-radius: 8px;border-radius: 10px;") %>
        			<%= other_user.name.titleize %>
        			<% end %>
        		</li>
        		<% end %>
        		<% end %>
        	</ul>
        </td>
      </tr>      
    </tbody>
  </table>
</div>
 