config/routes.rb
Rails.application.routes.draw do
  get 'all_users/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index'
resources :posts do	
	# resources :comments
	member do 
		post :like
		post :unlike
		get :all_likes
		post :comment
		post :remove_comment
		get :user_profile
	end
	collection do		
		get :my_post
	end
	
end
# resources :likes do
# 	collection do
# 		get :all_likes
# 	end
# end
resources :friendships do
	member do
		post :accept
		post :reject
	end
	collection do 
		get :myfriends
	end
end
resources :conversations do 
	resources :messages
end
# mount ActionCable.server => '/cable'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user , inverse_of: :friendships
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :authenticate_user!
	def index
		binding.pry
		@friends=Friendship.where(friend_id: current_user.id, status: 'Pending').includes(:user)
	end
	
	def myfriends
		@friends=current_user.inverse_friendships
		unless @friends.present?
			@friends = current_user.friendships
		end
		# @friends=Friendship.where('( user_id != ?) and status=?',current_user,"Accepted")		
	end
	def create	
		# binding.pry
		@user = User.find(current_user.id)
		@friend = User.find(params[:friend_id])
		# @t=Friendship.where(user_id: @user , friend_id: @friend).exists?
		 @t = Friendship.where('( user_id = ? and friend_id =? ) or (friend_id = ? and user_id=?)',@user,@friend,@user,@friend).exists?		
		if @t == true
			redirect_to root_path
		else
			
			@friendship = current_user.friendships.build(:friend_id => params[:friend_id],:status => "Pending")
			if @friendship.save				
				flash[:notice] = "Added friend."
				redirect_to all_users_index_path
			else
				flash[:error] = "Error occurred when adding friend."
				redirect_to all_users_index_path
			end
		end
	end
	def update
		binding.pry
		@friendship = current_user.friendships.build(:friend_id => params[:friend_id],:status => "Accepted")
		if @friendship.update
			redirect_to all_users_index_path
		else
			redirect_to all_users_index_path
		end
	end
	def destroy
		@curr=current_user.id
		@para=Friendship.where(user_id: params[:id],friend_id: @curr)
		@para.destroy(@para.ids)
		redirect_to friendrequests_path
	end

	def accept
		# binding.pry
		friendship = Friendship.find_by(user_id: params[:id])
		if friendship.present?
			friendship.update(status: 'Accepted')
			# current_user.friendships.create(:friend_id => params[:id],:status => "Accepted")
		else
			# alert[:message] = "Sorry Not found"
		end
		redirect_to friendships_path
		
	end

	def reject
		friendship = Friendship.find_by(id: params[:id])
		if friendship.present?
			friendship.update(status: 'Rejected')
		else
			# alert[:message] = "Sorry Not found"
		end
		redirect_to friendships_path
		
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<body>
<div class="container">
  
  <table class="table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Image</th>
        <th colspan="4">Action</th>
      </tr>
    </thead>
      <%@friends.each do |friend|%>
    <tbody>
      <tr>
        <td><%=friend.user.name%></td>
        <td><%= image_tag(friend.user.try(:image).try(:url),:size => "260x180",style: "border-radius: 100%;") %></td>
        <td><%= link_to "Confirm",accept_friendship_path(friend.user_id) ,method: :post, class: "btn btn-info"%></td>
         <td><%= link_to "Reject",reject_friendship_path(friend) ,method: :post, class: "btn btn-info"%></td>
        <td><%= link_to "Details",friendships_path(:friend_id => friend), class: "btn btn-info"%></td>
      </tr>            
    </tbody>
    <%end%>
  </table>
</div>

</body>
</html>

app/views/friendships/myfriends.html.erb
<body>
<div class="container">
  
  <table class="table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Image</th>
        <th colspan="4">Action</th>
      </tr>
    </thead>


  <%@friends.each do |friend|%>
      
    <tbody>
      <tr>
        <td><%=friend.user.name%></td>
        <td><%= image_tag(friend.user.try(:image).try(:url),:size => "260x180",style: "border-radius: 100%;") %></td>
        
        <td><%= link_to "Profile",user_profile_post_path(current_user.id), class: "btn btn-info"%></td>
      </tr>            
    </tbody>
    <%end%>
  </table>
</div>

</body>
</html>