config/routes.rb
Rails.application.routes.draw do
  get 'all_users/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index'
resources :posts do	
	# resources :comments
	member do 
		post :like
		post :unlike
		get :all_likes
		post :comment
		post :remove_comment
		get :user_profile
	end
	collection do		
		get :my_post
	end
	
end
# resources :likes do
# 	collection do
# 		get :all_likes
# 	end
# end
resources :friendships do
	member do
		post :accept
		post :reject
	end
	collection do 
		get :myfriends
	end
end
resources :conversations do 
	resources :messages
end
# mount ActionCable.server => '/cable'
end

app/controllers/all_users_controller.rb
class AllUsersController < ApplicationController
  def index
	@users= User.where.not(id: current_user.id) 
  end
end

app/helpers/all_users_helper.rb
module AllUsersHelper
end

app/views/all_users/index.html.erb
<body>
  <div class="container">  
    <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>Email</th>
          <th>Name</th>
          <th colspan="4">Action</th>
        </tr>
      </thead>
      <%@users.each do |user|%>
      <tbody>
        <tr>
          <td><%= image_tag(user.image,:size => "260x180", style: "border-radius: 100%;") %></td>
          <td><%=user.email.titleize%></td>
          <td><%=user.name.titleize%></td>
          <td><%= link_to "Add friend",friendships_path(:friend_id => user) ,method: :post,class: "btn btn-success"%>
            <%= link_to "Message",friendships_path(:friend_id => user) ,method: :post,class: "btn btn-success"%>
          </td>
        </tr>            
      </tbody>
      <%end%>
    </table>
  </div>
</body>

app/views/all_users/new.html.erb
hiiii request is already send