config/routes.rb
Rails.application.routes.draw do
  get 'all_users/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index'
resources :posts do	
	# resources :comments
	member do 
		post :like
		post :unlike
		get :all_likes
		post :comment
		post :remove_comment
		get :user_profile
	end
	collection do		
		get :my_post
	end
	
end
# resources :likes do
# 	collection do
# 		get :all_likes
# 	end
# end
resources :friendships do
	member do
		post :accept
		post :reject
	end
	collection do 
		get :myfriends
	end
end
resources :conversations do 
	resources :messages
end
# mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord  
  belongs_to :user,optional: true
  has_many :comments, dependent: :destroy 
  has_many :likes, dependent: :destroy 
  has_many :liked_users, through: :likes, source: 'user', dependent: :destroy 
  mount_uploader :image, AvatarUploader

  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_comment,only:[:destroy]
	def index
		@posts=Post.all.order("created_at DESC").paginate(:page => params[:page],:per_page =>2)		
	end
	def new
		@post=current_user.posts.build
	end
	def create
		@post=current_user.posts.build(param_post)
		if @post.save!
			redirect_to posts_path  
		else
			render :new
		end
	end	
	def update

	end
	def destroy
		
	end
	def param_post
		params.require(:post).permit(:title,:image,:user_id)
	end
	def edit

	end
	def comment
		@post=Post.find(params[:id])
		@comment=@post.comments.new(comment: params[:comment],user_id: current_user.id )
		if @comment.save
			redirect_to post_path(@post)
		else 
			redirect_to post_path(@post)
		end
	end
	def remove_comment
		 @post = Post.find_by(id: params[:id])
		@comment  = @post .comments.find_by(id: params[:comment])
	 	if @comment.destroy
			redirect_to post_path(@post)
		else
			redirect_to post_path(@post)
		end
	end 

	def like
		# binding.pry
		@post=Post.find(params[:id])
		@like = @post.likes.new(user_id: current_user.id, like: "liked")		
		if @like.save
			redirect_to post_path(@post)
		else 
			redirect_to post_path(@post)
		end
		
	end
	def all_likes
		# binding.pry
		@post=Post.find(params[:id])	
		@likes=@post.liked_users
	end
	def user_profile
	end

	def unlike
		@post=Post.find(params[:id])
		@like = @post.likes.where(user_id: current_user.id, like: "liked")		
		if @like.present?
			@like.destroy_all
			redirect_to post_path(@post)
		else 
			redirect_to post_path(@post)
		end		
	end
	def show		
		@post=Post.find(params[:id])
		@my_like = 	@post.likes.where(user_id: current_user.id)
		@comments=Comment.where(post_id: @post).order("created_at DESC")
	end
	def my_post
		@posts=current_user.posts.all
	end 

	def find_post
		# binding.pry
		@post=Post.find(params[:post_id])
	end
	def find_comment	
		@comment=@post.comments.find(params[:id])
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<% @comments.each do |comment|%>
<div >
	<br>
<p class="post-title"><b><%= image_tag(comment.user.image,style: "height: 42px;border-top-left-radius: 8px;border-radius: 10px;") %>  <%=comment.user.name.titleize%></b>                <%= comment.comment%></p>

<abbr class="timeago" title="<%= comment.created_at.getutc.iso8601 %>">
  <%= comment.created_at.to_s %>
</abbr>
<%= link_to "Delete",remove_comment_post_path(comment: comment), method: :post, class:"btn btn-primary btn-sm"%>
</div>
<%end%>
<script type="text/javascript">
	jQuery(document).ready(function() {
  jQuery("abbr.timeago").timeago();
});
</script>
<%= render "posts/formcom"%>

app/views/posts/_form.html.erb
<div class="panel-body">
  <%=form_for @post do |f|%>   
  
  <div class="form-group">
        <label for="cc-name" class="control-label mb-1">Title</label>
        <%=f.text_field :title, class: "form-control","aria-required": "true","aria-invalid": "false",style: "width: 300px;height: 40px;"%>
      </div>
  <div class="form-group">
    <label for="lastname">Image *</label>
    <%=f.file_field :image, class:"form-control",text:"required",style: "width: 300px;height: 40px;"%>
    <span id="error_lastname" class="text-danger"></span>
  </div> 
    <%=f.submit "Submit", class:"btn btn-primary center" %>
  <%end%>
</div>



<script type="text/javascript">
  $(document).ready(function(){
$("#new_post").validate({
   rules: {
     "post[title]": {
       required: true,
       maxlength: 10
     }  
    
   },
   messages: {
     "post[title]": {
       required: "title is required.",
       maxlength: "Máximo 10 caracteres requeridos."
     }
   }
 });
 });
</script>  

app/views/posts/_formcom.html.erb
<%= form_tag("/posts/#{@post.id}/comment", method: "post") do %>

	<p>
		<%=label_tag :Comment%></br>
		<%=text_area_tag :comment%>
	</p>

	<p>
		<input type="submit" name="" value="comment" class="btn btn-primary ">
	</p>
<%end%>

app/views/posts/all_likes.html.erb
<div class="panel panel-danger">
	<div class="panel-heading"></div>
	<div class="panel-body"></div>
	<% @likes.each do |likee|%> 
	 <h2><%= image_tag(likee.image_url, :size => "40x30",class: 'image-responsive')%> 
	   <%=likee.name%></h2>	 
	<%end%>
</div>

app/views/posts/edit.html.erb
<div class="content mt-3">
	<div class="animated fadeIn">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<strong class="card-title">Edit post</strong>
					</div>
					<%=render 'form'%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<strong class="card-title"> <%= link_to "Make Post",new_post_path ,class: 'btn btn-primary'%></strong><br><br>

<div class="content mt-5">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-md-8">
        <div class="card" style="margin-left: 339px;">
          <div class="card-header">          
            <div class="card-body">
              <%@posts.each do |post|%>  
              <div class="panel panel-danger">

                <div class="panel-heading"> 
                  <%= image_tag(post.user.image,style: "height: 42px;border-top-left-radius: 8px;border-radius: 10px;") %>   <b><i>User_name ::</i> <%= post.user.name%></b>  
                                 
                </div>
                <div class="panel-heading post-title"><%=post.title%></div>
                <div class="panel-body" style="margin-left: 89px;">     
                  <%= image_tag(post.image,:size => "260x180") %> 
                  <div><%= time_ago_in_words(post.created_at)%>
                    <br>
                     <%= link_to "see more", post_path(post)%>
                  </div>
                </div>                             
              </div>                            
              <%end%>
              <%= will_paginate @posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, previous_label: "older", next_label: "newer",inner_window: 1,outer_window: 0%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/my_post.html.erb
<div class="content mt-5">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-md-8">
        <div class="card" style="margin-left: 339px;">
          <div class="card-header">          
            <div class="card-body">
              <%@posts.each do |post|%>  
              <div class="panel panel-danger">
              <div class="panel-heading post-title"><%=post.title%></div>
                <div class="panel-body" style="margin-left: 89px;">     
                  <%= image_tag(post.image, :size => "260x180") %> 
                  <div><%= time_ago_in_words(post.created_at)%>                            
                  </div>
                </div> 
                <h2>Comments::<%= post.comments.count %></h2>
	             <h2><%= post.likes.count %><%= link_to "Like",all_likes_post_path(post) , class: "btn" %></h2>                                           
              </div>                            
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  .post-title{ word-wrap: break-word;}
</style>

app/views/posts/new.html.erb
<div class="content mt-3">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <strong class="card-title"><h1>New Post</h1></strong>
          </div>
          <%=render 'form'%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="content mt-5">
	<div class="animated fadeIn">
		<div class="row">
			<div class="col-md-8">
				<div class="card" style="margin-left: 339px;">
					<div class="card-header">          
						<div class="card-body">
							<div class="panel panel-danger" id="aj">
								<div class="panel-heading"> <%=@post.title%></div>
								<div class="panel-body"><%= image_tag(@post.image_url, :size => "260x180",style: "margin-left: 20%;") %> 
								</div>
								
								<%= link_to " #{@post.likes.count} Likes", all_likes_post_path(@post.id) , class: "btn btn-primary", style: "margin-left: 109px;"%>
								<%if @my_like.present?%>
								<%= link_to "UnLike", unlike_post_path(@post.id) ,method: :post  ,  class: "btn btn-primary",
								style:"margin-left: 133px;"%>
								<%else%>
								<%= link_to "Like", like_post_path(@post),method: :post  , class: "btn btn-primary",  style: "margin-left: 133px;"  %>
								<%end%>
								<h4><%= @post.comments.count %> Comments ::</h4>
								<%= render 'posts/comment'%>
							</div> 
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>